name: flutter_hooks_lint_plugin
description: a lint plugin for flutter_hooks
repository: https://github.com/mj-hd/flutter_hooks_lint_plugin
version: 0.7.0

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.38.0"

dependencies:
  analyzer: ^9.0.0
  analyzer_plugin: ^0.13.8
  analysis_server_plugin: ^0.3.0
  logging: ^1.0.0
  yaml: ^3.1.0
  path: ^1.8.0
  args: ^2.3.0
  glob: ^2.0.0

dev_dependencies:
  flutter:
    sdk: flutter
  lints: 2.0.1
  test: ^1.21.1
  tuple: ^2.0.0
  flutter_hooks: ^0.21.3+1
  benchmark_harness: ^2.1.0
  analyzer_testing: any
  test_reflective_loader: any

executables:
  flutter_hooks_lint:
