name: flutter_hooks_lint_plugin
description: a lint plugin for flutter_hooks
repository: https://github.com/mj-hd/flutter_hooks_lint_plugin
version: 0.4.0

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  analyzer: ">=2.6.0 <4.1.0"
  analyzer_plugin: ">=0.8.0 <=0.10.0"
  logging: ^1.0.0
  yaml: ^3.1.0
  path: ^1.8.0
  args: ^2.3.0
  glob: ^2.0.0

dev_dependencies:
  flutter:
    sdk: flutter
  lints: 2.0.0
  test: 1.21.1
  tuple: 2.0.0
  flutter_hooks: 0.18.3
  benchmark_harness: 2.1.0

executables:
  flutter_hooks_lint:
